import * as fs from "fs";
import * as path from "path";

import { SEPOLIA } from "../config/zama";

/**
 * Emits `web/src/lib/deployments.ts` from the deployment artifacts.
 *
 *   npx hardhat run scripts/export-deployments.ts --network sepolia
 *
 * The frontend never hand-copies an address or an ABI. Redeploy, re-run this, and the app is in
 * step with the chain — a mismatch here is the kind of bug that only shows up in front of a judge.
 */
const NETWORK = "sepolia";
const OUT = path.resolve(__dirname, "../../web/src/lib/deployments.ts");

/** Only the surface the app actually calls, so the generated file stays readable. */
const KEEP: Record<string, string[]> = {
  StubPool: [
    "deposit",
    "withdraw",
    "sealDraw",
    "settleDraw",
    "voidDraw",
    "openStub",
    "claim",
    "confidentialBalanceOf",
    "confidentialBalanceAtSeal",
    "confidentialWinningsOf",
    "confidentialTotal",
    "stubOf",
    "stubOpened",
    "ticketOf",
    "draws",
    "currentDrawId",
    "drawInterval",
    "sealableAt",
    "voidableAt",
    "rolloverPrize",
    "token",
    "yieldSource",
    "owner",
    "DrawSealed",
    "DrawSettled",
    "DrawVoid",
    "StubOpened",
    "Deposited",
    "Withdrawn",
    "Claimed",
  ],
  MockYieldSource: ["accruedYield", "dripPerSecond", "prizePerInterval", "runwaySeconds", "asset"],
};

function abiFor(name: string) {
  const artifact = JSON.parse(
    fs.readFileSync(path.resolve(__dirname, `../deployments/${NETWORK}/${name}.json`), "utf8"),
  );
  const keep = new Set(KEEP[name] ?? []);
  const abi = artifact.abi.filter(
    (e: { type: string; name?: string }) =>
      e.type === "error" || (e.name !== undefined && keep.has(e.name)),
  );
  return { address: artifact.address as string, abi };
}

function main() {
  const pool = abiFor("StubPool");
  const yieldSource = abiFor("MockYieldSource");

  const body = `// Generated by contracts/scripts/export-deployments.ts — do not edit.
// Re-run after any deploy: npx hardhat run scripts/export-deployments.ts --network ${NETWORK}

export const CHAIN_ID = 11155111 as const;

export const ADDRESSES = {
  /** The pool. Ours. */
  pool: "${pool.address}",
  /** The mock prize reserve. Ours. */
  yieldSource: "${yieldSource.address}",
  /** Zama's Confidential USDC (Mock) — an ERC-7984 wrapper we do not deploy. */
  confidentialUSDC: "${SEPOLIA.confidentialUSDC}",
  /** Its underlying, with a public mint that serves as the faucet. */
  usdc: "${SEPOLIA.usdc}",
} as const;

export const POOL_ABI = ${JSON.stringify(pool.abi, null, 2)} as const;

export const YIELD_SOURCE_ABI = ${JSON.stringify(yieldSource.abi, null, 2)} as const;

/** Minimal ERC-20 surface: the faucet mint and the wrap approval. */
export const USDC_ABI = [
  { type: "function", name: "mint", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
] as const;

/** ERC-7984 surface the app touches on Zama's wrapper. */
export const CONFIDENTIAL_USDC_ABI = [
  { type: "function", name: "wrap", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bytes32" }] },
  { type: "function", name: "setOperator", stateMutability: "nonpayable", inputs: [{ name: "operator", type: "address" }, { name: "until", type: "uint48" }], outputs: [] },
  { type: "function", name: "isOperator", stateMutability: "view", inputs: [{ name: "holder", type: "address" }, { name: "spender", type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "confidentialBalanceOf", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "bytes32" }] },
  { type: "function", name: "underlying", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  // Unwrapping is two steps. \`unwrap\` burns the confidential balance and records a request keyed
  // by the resulting ciphertext handle; \`finalizeUnwrap\` releases the underlying once the KMS has
  // signed off on what that ciphertext decrypts to. A request left unfinalized strands the
  // underlying in the wrapper, which is why the app hunts for them.
  { type: "function", name: "unwrap", stateMutability: "nonpayable", inputs: [{ name: "from", type: "address" }, { name: "to", type: "address" }, { name: "encryptedAmount", type: "bytes32" }, { name: "inputProof", type: "bytes" }], outputs: [{ type: "bytes32" }] },
  { type: "function", name: "finalizeUnwrap", stateMutability: "nonpayable", inputs: [{ name: "unwrapRequestId", type: "bytes32" }, { name: "unwrapAmountCleartext", type: "uint64" }, { name: "decryptionProof", type: "bytes" }], outputs: [] },
  { type: "function", name: "unwrapRequester", stateMutability: "view", inputs: [{ name: "unwrapRequestId", type: "bytes32" }], outputs: [{ type: "address" }] },
  { type: "function", name: "unwrapAmount", stateMutability: "view", inputs: [{ name: "unwrapRequestId", type: "bytes32" }], outputs: [{ type: "bytes32" }] },
  { type: "event", name: "UnwrapRequested", inputs: [{ name: "receiver", type: "address", indexed: true }, { name: "unwrapRequestId", type: "bytes32", indexed: true }, { name: "amount", type: "bytes32", indexed: false }] },
] as const;
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log(`wrote ${OUT}`);
  console.log(`  pool         ${pool.address}  (${pool.abi.length} abi entries)`);
  console.log(`  yieldSource  ${yieldSource.address}  (${yieldSource.abi.length} abi entries)`);
}

main();
